// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]); 
		int countL = 0; 
		int countS = 0; 
		double ratio = 0;
		
		for(int i = 0; i <= n; i++){
			double random = Math.random(); 
			if(random > 0.5){
				countL++; 
			}
			else{
				countS++; 
			}
		}
		if(countL == 0 || countS == 0){
			System.out.println("> 0.5: " + countL + " times");
			System.out.println("<= 0.5: " + countS + " times");
		}
		else{
			if(countL>countS){
				ratio = (double) countS/countL;
			}else{
				ratio = (double) countL/countS;
			}
				
			System.out.println("> 0.5: " + countL + " times");
			System.out.println("<= 0.5: " + countS + " times");
			System.out.println("Ratio " + ratio);
		}
	}
}
